/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * LivroInsere.java
 *
 * Created on 17/12/2009, 01:42:33
 */

package epbd;

/**
 *
 * @author Administrador
 */
public class LivroModifica extends javax.swing.JFrame {

    /** Creates new form LivroInsere */
    public LivroModifica() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lISBN = new javax.swing.JLabel();
        lTitulo = new javax.swing.JLabel();
        lNome = new javax.swing.JLabel();
        lSobrenome = new javax.swing.JLabel();
        lAutor = new javax.swing.JLabel();
        lEditora = new javax.swing.JLabel();
        lCategoria = new javax.swing.JLabel();
        lPreco = new javax.swing.JLabel();
        lAno = new javax.swing.JLabel();
        lEstoqueMin = new javax.swing.JLabel();
        lResenhas = new javax.swing.JLabel();
        campoISBN = new javax.swing.JTextField();
        campoTitulo = new javax.swing.JTextField();
        campoEditora = new javax.swing.JTextField();
        comboCategoria = new javax.swing.JComboBox();
        campoPreco = new javax.swing.JTextField();
        scrollAutores = new javax.swing.JScrollPane();
        painelAutores = new javax.swing.JPanel();
        campoNome = new javax.swing.JTextField();
        campoSobrenome = new javax.swing.JTextField();
        campoEstoqueMin = new javax.swing.JTextField();
        scrollResenhas = new javax.swing.JScrollPane();
        bMaisAutor = new javax.swing.JButton();
        bMenosAutor = new javax.swing.JButton();
        bMaisResenha = new javax.swing.JButton();
        bMenosResenha = new javax.swing.JButton();
        campoAno = new javax.swing.JTextField();
        botaoAtualiza = new javax.swing.JButton();
        botaoCancela = new javax.swing.JButton();
        lSituacao = new javax.swing.JLabel();
        textoSituacao = new javax.swing.JTextField();
        botaoReativar = new javax.swing.JButton();
        campoEstoque = new javax.swing.JTextField();
        lEstoque = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Atualizar livro");

        lISBN.setText("ISBN");

        lTitulo.setText("Título");

        lNome.setText("Nome");

        lSobrenome.setText("Sobrenome");

        lAutor.setText("Autor(es)");

        lEditora.setText("Editora");

        lCategoria.setText("Categoria");

        lPreco.setText("Preço");

        lAno.setText("Ano");

        lEstoqueMin.setText("Quantidade Mínima em estoque");

        lResenhas.setText("Resenha(s)");

        campoISBN.setEnabled(false);

        comboCategoria.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        campoPreco.setText("$0,00");

        campoNome.setText("Nome");

        campoSobrenome.setText("Sobrenome");

        javax.swing.GroupLayout painelAutoresLayout = new javax.swing.GroupLayout(painelAutores);
        painelAutores.setLayout(painelAutoresLayout);
        painelAutoresLayout.setHorizontalGroup(
            painelAutoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelAutoresLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(campoNome, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoSobrenome, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                .addContainerGap())
        );
        painelAutoresLayout.setVerticalGroup(
            painelAutoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelAutoresLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelAutoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoSobrenome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(69, Short.MAX_VALUE))
        );

        scrollAutores.setViewportView(painelAutores);

        campoEstoqueMin.setText("0");

        bMaisAutor.setText("Mais");

        bMenosAutor.setText("Menos");
        bMenosAutor.setEnabled(false);

        bMaisResenha.setText("Mais");
        bMaisResenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bMaisResenhaActionPerformed(evt);
            }
        });

        bMenosResenha.setText("Menos");
        bMenosResenha.setEnabled(false);

        campoAno.setText("YYYY");

        botaoAtualiza.setText("Atualiza");

        botaoCancela.setText("Cancela");

        lSituacao.setText("Situacao");

        textoSituacao.setEditable(false);
        textoSituacao.setText("Apagado/Ativo");

        botaoReativar.setText("Reativar");
        botaoReativar.setEnabled(false);

        campoEstoque.setEditable(false);
        campoEstoque.setText("MMM");

        lEstoque.setText("Estoque");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lResenhas)
                    .addComponent(lTitulo)
                    .addComponent(lISBN)
                    .addComponent(lAutor)
                    .addComponent(lEditora)
                    .addComponent(lCategoria)
                    .addComponent(lPreco))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botaoAtualiza, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(campoISBN, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(95, 95, 95)
                                .addComponent(lSituacao)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textoSituacao, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(comboCategoria, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(campoEditora, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lAno)
                                            .addComponent(lEstoque)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(campoPreco, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
                                        .addGap(18, 18, 18)
                                        .addComponent(lEstoqueMin)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(campoAno, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
                                    .addComponent(campoEstoqueMin, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
                                    .addComponent(campoEstoque)))
                            .addComponent(campoTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 313, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botaoReativar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(scrollAutores, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(scrollResenhas, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 319, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lNome)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lSobrenome))
                            .addComponent(botaoCancela))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(bMenosAutor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bMaisResenha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bMenosResenha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bMaisAutor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lISBN)
                    .addComponent(campoISBN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textoSituacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoReativar)
                    .addComponent(lSituacao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lTitulo)
                    .addComponent(campoTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lSobrenome)
                    .addComponent(lNome))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(bMaisAutor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bMenosAutor))
                    .addComponent(lAutor)
                    .addComponent(scrollAutores, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(campoEditora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lEditora))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lCategoria)
                            .addComponent(comboCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(campoAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lAno))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(campoEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lEstoque))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lPreco)
                    .addComponent(lEstoqueMin)
                    .addComponent(campoEstoqueMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lResenhas)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(bMaisResenha)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bMenosResenha))
                        .addComponent(scrollResenhas, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botaoCancela)
                    .addComponent(botaoAtualiza))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bMaisResenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bMaisResenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bMaisResenhaActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LivroModifica().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bMaisAutor;
    private javax.swing.JButton bMaisResenha;
    private javax.swing.JButton bMenosAutor;
    private javax.swing.JButton bMenosResenha;
    private javax.swing.JButton botaoAtualiza;
    private javax.swing.JButton botaoCancela;
    private javax.swing.JButton botaoReativar;
    private javax.swing.JTextField campoAno;
    private javax.swing.JTextField campoEditora;
    private javax.swing.JTextField campoEstoque;
    private javax.swing.JTextField campoEstoqueMin;
    private javax.swing.JTextField campoISBN;
    private javax.swing.JTextField campoNome;
    private javax.swing.JTextField campoPreco;
    private javax.swing.JTextField campoSobrenome;
    private javax.swing.JTextField campoTitulo;
    private javax.swing.JComboBox comboCategoria;
    private javax.swing.JLabel lAno;
    private javax.swing.JLabel lAutor;
    private javax.swing.JLabel lCategoria;
    private javax.swing.JLabel lEditora;
    private javax.swing.JLabel lEstoque;
    private javax.swing.JLabel lEstoqueMin;
    private javax.swing.JLabel lISBN;
    private javax.swing.JLabel lNome;
    private javax.swing.JLabel lPreco;
    private javax.swing.JLabel lResenhas;
    private javax.swing.JLabel lSituacao;
    private javax.swing.JLabel lSobrenome;
    private javax.swing.JLabel lTitulo;
    private javax.swing.JPanel painelAutores;
    private javax.swing.JScrollPane scrollAutores;
    private javax.swing.JScrollPane scrollResenhas;
    private javax.swing.JTextField textoSituacao;
    // End of variables declaration//GEN-END:variables

}
