/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Manutencao.java
 *
 * Created on 17/12/2009, 01:04:54
 */

package epbd;

/**
 *
 * @author Administrador
 */
public class Manutencao extends javax.swing.JFrame {

    /** Creates new form Manutencao */
    public Manutencao() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelCategoria = new javax.swing.JPanel();
        lCategoria = new javax.swing.JLabel();
        bMaisCategoria = new javax.swing.JButton();
        bMenosCategoria = new javax.swing.JButton();
        scrollCategoria = new javax.swing.JScrollPane();
        painelEstado = new javax.swing.JPanel();
        lEstado = new javax.swing.JLabel();
        bMaisEstado = new javax.swing.JButton();
        bMenosEstado = new javax.swing.JButton();
        scrollEstado = new javax.swing.JScrollPane();
        painelBandeira = new javax.swing.JPanel();
        lBandeira = new javax.swing.JLabel();
        bMaisBandeira = new javax.swing.JButton();
        bMenosBandeira = new javax.swing.JButton();
        scrollBandeira = new javax.swing.JScrollPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Manutenção do sistema");

        lCategoria.setText("Categoria");

        bMaisCategoria.setText("Mais");

        bMenosCategoria.setText("Menos");
        bMenosCategoria.setEnabled(false);

        javax.swing.GroupLayout painelCategoriaLayout = new javax.swing.GroupLayout(painelCategoria);
        painelCategoria.setLayout(painelCategoriaLayout);
        painelCategoriaLayout.setHorizontalGroup(
            painelCategoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelCategoriaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lCategoria)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollCategoria, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelCategoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bMaisCategoria, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bMenosCategoria, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        painelCategoriaLayout.setVerticalGroup(
            painelCategoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelCategoriaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelCategoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bMaisCategoria)
                    .addComponent(lCategoria))
                .addGap(7, 7, 7)
                .addComponent(bMenosCategoria)
                .addContainerGap(47, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelCategoriaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(scrollCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        lEstado.setText("Estado");

        bMaisEstado.setText("Mais");

        bMenosEstado.setText("Menos");
        bMenosEstado.setEnabled(false);

        javax.swing.GroupLayout painelEstadoLayout = new javax.swing.GroupLayout(painelEstado);
        painelEstado.setLayout(painelEstadoLayout);
        painelEstadoLayout.setHorizontalGroup(
            painelEstadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelEstadoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lEstado)
                .addGap(18, 18, 18)
                .addComponent(scrollEstado, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelEstadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bMaisEstado, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bMenosEstado, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        painelEstadoLayout.setVerticalGroup(
            painelEstadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelEstadoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelEstadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelEstadoLayout.createSequentialGroup()
                        .addGroup(painelEstadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bMaisEstado)
                            .addComponent(lEstado))
                        .addGap(7, 7, 7)
                        .addComponent(bMenosEstado))
                    .addComponent(scrollEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lBandeira.setText("Bandeira");

        bMaisBandeira.setText("Mais");

        bMenosBandeira.setText("Menos");
        bMenosBandeira.setEnabled(false);

        javax.swing.GroupLayout painelBandeiraLayout = new javax.swing.GroupLayout(painelBandeira);
        painelBandeira.setLayout(painelBandeiraLayout);
        painelBandeiraLayout.setHorizontalGroup(
            painelBandeiraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelBandeiraLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lBandeira)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(scrollBandeira, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelBandeiraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bMaisBandeira, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bMenosBandeira, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        painelBandeiraLayout.setVerticalGroup(
            painelBandeiraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelBandeiraLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelBandeiraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bMaisBandeira)
                    .addComponent(lBandeira))
                .addGap(7, 7, 7)
                .addComponent(bMenosBandeira)
                .addContainerGap(47, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelBandeiraLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(scrollBandeira, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(painelBandeira, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(painelEstado, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(painelCategoria, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(painelCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painelEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painelBandeira, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Manutencao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bMaisBandeira;
    private javax.swing.JButton bMaisCategoria;
    private javax.swing.JButton bMaisEstado;
    private javax.swing.JButton bMenosBandeira;
    private javax.swing.JButton bMenosCategoria;
    private javax.swing.JButton bMenosEstado;
    private javax.swing.JLabel lBandeira;
    private javax.swing.JLabel lCategoria;
    private javax.swing.JLabel lEstado;
    private javax.swing.JPanel painelBandeira;
    private javax.swing.JPanel painelCategoria;
    private javax.swing.JPanel painelEstado;
    private javax.swing.JScrollPane scrollBandeira;
    private javax.swing.JScrollPane scrollCategoria;
    private javax.swing.JScrollPane scrollEstado;
    // End of variables declaration//GEN-END:variables

}
