/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PedidoLivro.java
 *
 * Created on 17/12/2009, 01:25:56
 */

package epbd;

/**
 *
 * @author Administrador
 */
public class PedidoLivro extends javax.swing.JFrame {

    /** Creates new form PedidoLivro */
    public PedidoLivro() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textoPendentes = new javax.swing.JTextField();
        textoNumPedidos = new javax.swing.JTextField();
        lISBN = new javax.swing.JLabel();
        lTitulo = new javax.swing.JLabel();
        lAutor = new javax.swing.JLabel();
        lEstoque = new javax.swing.JLabel();
        lMinimo = new javax.swing.JLabel();
        lEncomendado = new javax.swing.JLabel();
        botaoAnterior = new javax.swing.JButton();
        botaoProximo = new javax.swing.JButton();
        botaoIgnorar = new javax.swing.JButton();
        botaoEnviar = new javax.swing.JButton();
        botaoCancelar = new javax.swing.JButton();
        textoPedidoID = new javax.swing.JTextField();
        campoEncomendada = new javax.swing.JTextField();
        textoISBN = new javax.swing.JTextField();
        textoAutores = new javax.swing.JTextField();
        textoEstoque = new javax.swing.JTextField();
        textoMinimo = new javax.swing.JTextField();
        textoTitulo = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Realizar Pedidos");

        textoPendentes.setEditable(false);
        textoPendentes.setText("Ordem pendente 1 de N");
        textoPendentes.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        textoNumPedidos.setEditable(false);
        textoNumPedidos.setText("# pedidos confirmados");
        textoNumPedidos.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lISBN.setText("ISBN");

        lTitulo.setText("Título");

        lAutor.setText("Autor(es)");

        lEstoque.setText("Quantidade em estoque");

        lMinimo.setText("Mínimo requerido");

        lEncomendado.setText("Quantidade a encomendar");

        botaoAnterior.setText("<< Pedido Anterior");

        botaoProximo.setText("Próximo Pedido >>");

        botaoIgnorar.setText("Ignorar Pedido >>");

        botaoEnviar.setText("Enviar Pedidos");
        botaoEnviar.setEnabled(false);

        botaoCancelar.setText("Cancelar");

        textoPedidoID.setEditable(false);
        textoPedidoID.setText("Ordem # K");
        textoPedidoID.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        textoPedidoID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoPedidoIDActionPerformed(evt);
            }
        });

        campoEncomendada.setText("MMM");

        textoISBN.setEditable(false);
        textoISBN.setText("isbn");

        textoAutores.setEditable(false);
        textoAutores.setText("autor1, autor2, autor3");

        textoEstoque.setEditable(false);
        textoEstoque.setText("XXX");

        textoMinimo.setEditable(false);
        textoMinimo.setText("YYY");

        textoTitulo.setEditable(false);
        textoTitulo.setText("titulo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(textoNumPedidos, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                            .addComponent(textoPendentes, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lEncomendado)
                            .addComponent(lMinimo)
                            .addComponent(lEstoque)
                            .addComponent(lAutor)
                            .addComponent(lTitulo)
                            .addComponent(lISBN))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(textoEstoque, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                    .addComponent(textoMinimo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                    .addComponent(textoAutores, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                    .addComponent(textoTitulo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                    .addComponent(textoISBN, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                    .addComponent(textoPedidoID, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                    .addComponent(campoEncomendada, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botaoAnterior, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                    .addComponent(botaoIgnorar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                    .addComponent(botaoProximo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                    .addComponent(botaoEnviar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                    .addComponent(botaoCancelar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoPendentes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoAnterior)
                    .addComponent(textoPedidoID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoNumPedidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoIgnorar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoProximo)
                    .addComponent(textoISBN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lISBN))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lTitulo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoAutores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lAutor))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lEstoque))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoMinimo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoEnviar)
                    .addComponent(lMinimo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lEncomendado)
                    .addComponent(campoEncomendada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoCancelar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textoPedidoIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoPedidoIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoPedidoIDActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PedidoLivro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoAnterior;
    private javax.swing.JButton botaoCancelar;
    private javax.swing.JButton botaoEnviar;
    private javax.swing.JButton botaoIgnorar;
    private javax.swing.JButton botaoProximo;
    private javax.swing.JTextField campoEncomendada;
    private javax.swing.JLabel lAutor;
    private javax.swing.JLabel lEncomendado;
    private javax.swing.JLabel lEstoque;
    private javax.swing.JLabel lISBN;
    private javax.swing.JLabel lMinimo;
    private javax.swing.JLabel lTitulo;
    private javax.swing.JTextField textoAutores;
    private javax.swing.JTextField textoEstoque;
    private javax.swing.JTextField textoISBN;
    private javax.swing.JTextField textoMinimo;
    private javax.swing.JTextField textoNumPedidos;
    private javax.swing.JTextField textoPedidoID;
    private javax.swing.JTextField textoPendentes;
    private javax.swing.JTextField textoTitulo;
    // End of variables declaration//GEN-END:variables

}
