/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TelaDeBoasVindas.java
 *
 * Created on 16/12/2009, 22:33:27
 */

package epbd;

import java.awt.Font;
import java.awt.Graphics;
import javax.swing.ButtonGroup;

/**
 *
 * @author Administrador
 */
public class TelaDeBoasVindas extends javax.swing.JFrame {

    /** Creates new form TelaDeBoasVindas */
    public TelaDeBoasVindas() {
        initComponents();
        grupoOpcoes = new ButtonGroup();
        grupoOpcoes.add(radioAdmin);
        grupoOpcoes.add(radioBusca);
        grupoOpcoes.add(radioClienteC);
        grupoOpcoes.add(radioClienteN);
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoOpcoes = new javax.swing.ButtonGroup();
        radioBusca = new javax.swing.JRadioButton();
        radioClienteN = new javax.swing.JRadioButton();
        radioClienteC = new javax.swing.JRadioButton();
        radioAdmin = new javax.swing.JRadioButton();
        botaoEntrar = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Bem-Vindo à loja Best Book Buy!");

        radioBusca.setSelected(true);
        radioBusca.setText("Somente busca");
        radioBusca.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                radioBuscaItemStateChanged(evt);
            }
        });

        radioClienteN.setText("Cliente novo");

        radioClienteC.setText("Cliente cadastrado");

        radioAdmin.setText("Administrador");

        botaoEntrar.setText("ENTRAR");

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("Best Book Buy [3b.com]");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(radioAdmin)
                    .addComponent(radioClienteC, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                    .addComponent(radioClienteN)
                    .addComponent(radioBusca)
                    .addComponent(botaoEntrar, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                    .addComponent(jLabel1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(radioBusca)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioClienteN)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioClienteC)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioAdmin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botaoEntrar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void radioBuscaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_radioBuscaItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_radioBuscaItemStateChanged

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaDeBoasVindas().setVisible(true);
                
                
            }
        });
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton botaoEntrar;
    private javax.swing.ButtonGroup grupoOpcoes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton radioAdmin;
    private javax.swing.JRadioButton radioBusca;
    private javax.swing.JRadioButton radioClienteC;
    private javax.swing.JRadioButton radioClienteN;
    // End of variables declaration//GEN-END:variables

    
}
