/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaceGrafica;

import COO.ArquivoConf;
import java.awt.Color;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.text.BadLocationException;
import javax.swing.text.DefaultHighlighter;

/**
 *
 * @author Fernanda
 */
public class Ctrl_F extends javax.swing.JFrame {

    /**
     * Creates new form Ctrl_F
     */
    public Ctrl_F(String arquivo, String busca) throws BadLocationException {
        Ctrl_F.arquivo = arquivo;
        Ctrl_F.busca = busca;
        cont = 0;
        initComponents();
        inicializaTexto();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        texto = new javax.swing.JTextPane();
        seguinte = new javax.swing.JButton();
        anterior = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        Busca_Palavra = new javax.swing.JMenu();
        BuscarPalavra = new javax.swing.JMenuItem();
        editar = new javax.swing.JMenu();
        TipoDeBuscaMenu = new javax.swing.JMenuItem();
        visualizarOutroArquivo = new javax.swing.JMenuItem();
        Sair = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        texto.setEditable(false);
        jScrollPane2.setViewportView(texto);

        seguinte.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        seguinte.setText("Seguinte");
        seguinte.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                seguinteMousePressed(evt);
            }
        });

        anterior.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        anterior.setText("Anterior");
        anterior.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                anteriorMousePressed(evt);
            }
        });

        Busca_Palavra.setText("Arquivo");

        BuscarPalavra.setText("Buscar Palavra");
        BuscarPalavra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BuscarPalavraMousePressed(evt);
            }
        });
        Busca_Palavra.add(BuscarPalavra);

        jMenuBar1.add(Busca_Palavra);

        editar.setText("Editar");

        TipoDeBuscaMenu.setText("Tipo de Busca");
        TipoDeBuscaMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TipoDeBuscaMenuMousePressed(evt);
            }
        });
        editar.add(TipoDeBuscaMenu);

        visualizarOutroArquivo.setText("Visualizar outro arquivo");
        visualizarOutroArquivo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                visualizarOutroArquivoMousePressed(evt);
            }
        });
        editar.add(visualizarOutroArquivo);

        jMenuBar1.add(editar);

        Sair.setText("Sair");
        Sair.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Sair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                SairMousePressed(evt);
            }
        });
        jMenuBar1.add(Sair);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 499, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(112, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(anterior)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(seguinte)
                .addGap(58, 58, 58))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(48, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 565, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(seguinte)
                    .addComponent(anterior))
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void seguinteMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_seguinteMousePressed
        // TODO add your handling code here:
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                for (int cont = indices.size() - 1; cont >= 0; cont--) {
                    System.out.println(indices.get(cont));
                }
                cont++;
                if (cont == indices.size()-1) {
                    cont = 0;
                }

                texto.select(indices.get(cont), indices.get(cont) + busca.length());
                texto.requestFocusInWindow();
                texto.setSelectedTextColor(Color.red);
            }
        });
    }//GEN-LAST:event_seguinteMousePressed

    private void anteriorMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_anteriorMousePressed
        // TODO add your handling code here:
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                cont--;
                if (cont < 0) {
                    cont = indices.size()-2;
                }

                texto.select(indices.get(cont), indices.get(cont) + busca.length());
                texto.requestFocusInWindow();
                texto.setSelectedTextColor(Color.red);
            }
        });
    }//GEN-LAST:event_anteriorMousePressed

    private void BuscarPalavraMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BuscarPalavraMousePressed
        // TODO add your handling code here:
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new TelaBusca().setVisible(true);
                dispose();
            }
        });
    }//GEN-LAST:event_BuscarPalavraMousePressed

    private void SairMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SairMousePressed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_SairMousePressed

    private void TipoDeBuscaMenuMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TipoDeBuscaMenuMousePressed
        // TODO add your handling code here:
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new TipoDeBusca(busca).setVisible(true);
                dispose();
            }
        });
    }//GEN-LAST:event_TipoDeBuscaMenuMousePressed

    private void visualizarOutroArquivoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_visualizarOutroArquivoMousePressed
        // TODO add your handling code here:
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new ArquivosContemPalavra(busca).setVisible(true);
                dispose();
            }
        });
    }//GEN-LAST:event_visualizarOutroArquivoMousePressed

    private void inicializaTexto () {
        String textoArquivo = null;
        for(int i = 0; i<ArquivoConf.Arquivos.size(); i++) {
            if (arquivo.contains( ArquivoConf.Arquivos.get(i).nome) == true) {
                textoArquivo = ArquivoConf.Arquivos.get(i).texto;
                texto.setText(textoArquivo);
            }
        }
        int tamanhoTexto = textoArquivo.length();
        int pos = 0;
        indices = new ArrayList<>();
        try {
            DefaultHighlighter.DefaultHighlightPainter highlightPainter = new DefaultHighlighter.DefaultHighlightPainter(Color.yellow); //marca-texto

            while (pos <= tamanhoTexto) {
                textoArquivo = textoArquivo.toLowerCase();
                int comeca = textoArquivo.indexOf(busca, pos);
                indices.add(comeca);
                texto.getHighlighter().addHighlight(comeca, comeca+busca.length(), highlightPainter);
                texto.setFocusable(true);
                pos = comeca + busca.length();
            }
            boolean continua = true;
            while (continua) {
                if (indices.contains(-1)) {
                    indices.remove(-1);
                }
                else {
                    continua = false;
                }
            }
            
        }
        catch (BadLocationException b) {
            b.printStackTrace();
        }
        texto.select(indices.get(0), indices.get(0)+busca.length());
        texto.setSelectedTextColor(Color.red);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ctrl_F.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ctrl_F.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ctrl_F.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ctrl_F.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                try {
                   new Ctrl_F(arquivo, busca).setVisible(true);
                } catch (BadLocationException ex) {
                    Logger.getLogger(Ctrl_F.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
        
       
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Busca_Palavra;
    private javax.swing.JMenuItem BuscarPalavra;
    private javax.swing.JMenu Sair;
    private javax.swing.JMenuItem TipoDeBuscaMenu;
    private javax.swing.JButton anterior;
    private javax.swing.JMenu editar;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton seguinte;
    private javax.swing.JTextPane texto;
    private javax.swing.JMenuItem visualizarOutroArquivo;
    // End of variables declaration//GEN-END:variables
    private static String arquivo;
    private static String busca;
    private static ArrayList <Integer> indices;
    private static int cont;
}
