CREATE SCHEMA BDET

CREATE TABLE BDET.ESTADO(	 	 	 	 	 	 	 	 	 	 
SIGLA		CHAR(2)		NOT NULL,
PRIMARY KEY(SIGLA)
);


CREATE TABLE BDET.EDITORA(
CNPJ		CHAR(14)		NOT NULL,
NOME		VARCHAR(15),
PRIMARY KEY(CNPJ)
);


CREATE TABLE BDET.CATEGORIA(	 	 	 	 	 	 	 	 	 	 
NOME		VARCHAR(15)		NOT NULL,
PRIMARY KEY(NOME)
);


CREATE TABLE BDET.LIVRO(
ISBN		INT				NOT NULL,
CAT_NOME	VARCHAR(15)		NOT NULL,
EDITORA		CHAR(14)		NOT NULL,
QTD_ESTOQUE	INT				DEFAULT 0,
QTD_MIN		INT				DEFAULT 0,
PRECO		DECIMAL(4,2)	NOT NULL,
APAGADO		BOOLEAN,
PRIMARY KEY(ISBN)
FOREIGN KEY(CAT_NOME) REFERENCES BDET.CATEGORIA(NOME),
FOREIGN KEY(EDITORA) REFERENCES BDET.EDITORA(CNPJ)
);


CREATE TABLE BDET.RESENHA(
ISBN		INT		NOT NULL,
TEXTO		VARCHAR(140),
PRIMARY KEY(ISBN, TEXTO),
FOREIGN KEY(ISBN) REFERENCES LIVRO(ISBN)
);


CREATE TABLE BDET.AUTOR(
ID			INT		NOT NULL,
NOME		VARCHAR(15),
SOBRENOME	VARCHAR(15),
PRIMARY KEY(ID)
);


CREATE TABLE BDET.ESCREVE(
ID_AUTOR	INT		NOT NULL,
ISBN		INT 	NOT NULL,
PRIMARY KEY(ID_AUTOR, ISBN),
FOREIGN KEY(ID_AUTOR) REFERENCES BDET.AUTOR(ID),
FOREIGN KEY(ISBN) REFERENCES BDET.LIVRO(ISBN)
);


CREATE TABLE BDET.USUARIO(
USERNAME	VARCHAR(8)	NOT NULL	DEFAULT 'TEMP_USR',
SENHA		INT			NOT NULL	DEFAULT 0,
NOME		VARCHAR(15),
SOBRENOME	VARCHAR(15),
ENDERECO	VARCHAR(140),
CIDADE		VARCHAR[20],
SIGLA_ESTADO	CHAR(2),
CEP		INT(8),
PRIMARY KEY(USERNAME),
FOREIGN KEY(SIGLA_ESTADO) REFERENCES ESTADO(SIGLA)
);


CREATE TABLE BDET.EMPRESA_CC(
BANDEIRA	VARCHAR(10)	NOT NULL,
PRIMARY KEY(BANDEIRA)
);


CREATE TABLE BDET.CARTAO(
BANDEIRA	VARCHAR(10)	NOT NULL,
NUMERO		VARCHAR(16)	NOT NULL,
DT_VALIDADE	INTERVAL,				//ANO-MÊS
PRIMARY KEY(BANDEIRA, NUMERO),
FOREIGN KEY(BANDEIRA) REFERENCES BDET.EMPRESA_CC(BANDEIRA)
);


CREATE TABLE BDET.CLIENTE(
USERNAME	VARCHAR(8)	NOT NULL,
CC_BANDEIRA	VARCHAR(10)	NOT NULL,
CC_NUMERO		CHAR(16)	NOT NULL,
PRIMARY KEY(USERNAME)
FOREIGN KEY(USERNAME) REFERENCES BDET.USUARIO(USERNAME),
FOREIGN KEY(CC_BANDEIRA) REFERENCES BDET.EMPRESA_CC(BANDEIRA),
FOREIGN KEY(CC_NUMERO) REFERENCES BDET.CARTAO(NUMERO)
);


CREATE TABLE BDET.ADMINISTRADOR(
USERNAME	VARCHAR(8)	NOT NULL,
DT_CONTRAT	DATE		NOT NULL,
PRIMARY KEY(USERNAME, DT_CONTRAT)
FOREIGN KEY(USERNAME) REFERENCES BDET.USUARIO(USERNAME)
);


CREATE TABLE BDET.TELEFONE_ADM(
USERNAME	VARCHAR(8)	NOT NULL,
DT_CONTRAT	DATE		NOT NULL,
TELEFONE	INT,
PRIMARY KEY(USERNAME, DT_CONTRAT, TELEFONE)
FOREIGN KEY(USERNAME) REFERENCES BDET.ADMINISTRADOR(USERNAME),
FOREIGN KEY(DT_CONTRAT) REFERENCES BDET.ADMINISTRADOR(DT_CONTRAT),
);


CREATE TABLE BDET.TRANSACAO(
USERNAME	VARCHAR(8)	NOT NULL,
DATA		DATE		NOT NULL,
HORA		TIME,		NOT NULL,
CATEGORIA	VARCHAR(15),
VALOR_TOTAL	MONEY,
PRIMARY KEY(USERNAME, DATA, HORA),
FOREIGN KEY(USERNAME) REFERENCES USUARIO(USERNAME)
);


CREATE TABLE BDET.COLOCA_CARRINHO(
USERNAME	VARCHAR[15]	NOT NULL,
ISBN		INT			NOT NULL,
QTD			INT,
PRIMARY KEY(USERNAME, ISBN),
FOREIGN KEY(USERNAME) REFERENCES BDET.CLIENTE(USERNAME),
FOREIGN KEY(ISBN) REFERENCES BDET.LIVRO(ISBN));
);


CREATE BDET.PEDIDO(	 	 	 	 	 	 	 	 	 	 
USERNAME    VARCHAR(15)	NOT NULL,
DT_CONTRAT	DATE		NOT NULL,
ISBN	    INT			NOT NULL,
DATA	    DATE,
HORA		TIME,
QTD			INT			DEFAULT 1,F
PRIMARY KEY(USERNAME, DT_CONTRATO, ISBN),
FOREIGN KEY(USERNAME) REFERENCES BDET.ADMINISTRADOR(USERNAME),
FOREIGN KEY(DT_CONTRAT) REFERENCES BDET.ADMINISTRADOR(DT_CONTRAT),
FOREIGN KEY(ISBN) REFERENCES BDET.LIVRO(ISBN));


CREATE TABLE BDET.CONTEM(	 	 	 	 	 	 	 	 	 	 
USERNAME	VARCHAR(8)	NOT NULL,
DATA		DATE		NOT NULL,
HORA		TIME,		NOT NULL,
ISBN		INT 	NOT NULL,
QTD			INT,
PRIMARY KEY(USERNAME, DATA, HORA, ISBN),
FOREIGN KEY(DATA) REFERENCES BDET.TRANSACAO(DATA),
FOREIGN KEY(HORA) REFERENCES BDET.TRANSACAO(HORA),
FOREIGN KEY(ISBN) REFERENCES BDET.LIVRO(ISBN)
);