CREATE SCHEMA BDET

CREATE TABLE BDET.ESTADO(	 	 	 	 	 	 	 	 	 	 
SIGLA		CHAR(2)		NOT NULL,
PRIMARY KEY(SIGLA)
);


CREATE TABLE BDET.EDITORA(
CNPJ		CHAR(14)		NOT NULL,
NOME		VARCHAR(15),
PRIMARY KEY(CNPJ)
);


CREATE TABLE BDET.CATEGORIA(	 	 	 	 	 	 	 	 	 	 
NOME		VARCHAR(15)		NOT NULL,
PRIMARY KEY(NOME)
);


CREATE TABLE BDET.LIVRO(
ISBN		BIGINT				NOT NULL,
TITULO		VARCHAR(50)		NOT NULL,
CAT_NOME	VARCHAR(15)		NOT NULL,
E_CNPJ		CHAR(14)		NOT NULL,
QTD_ESTOQUE	INT				DEFAULT 0,
QTD_MIN		INT				DEFAULT 0,
PRECO		DECIMAL(4,2)	NOT NULL,
APAGADO		BOOLEAN,
PRIMARY KEY(ISBN),
FOREIGN KEY(CAT_NOME) REFERENCES BDET.CATEGORIA(NOME)
	ON DELETE RESTRICT ON UPDATE CASCADE,
FOREIGN KEY(E_CNPJ) REFERENCES BDET.EDITORA(CNPJ)
	ON DELETE RESTRICT ON UPDATE CASCADE
);


CREATE TABLE BDET.RESENHA(
ISBN		BIGINT		NOT NULL,
TEXTO		VARCHAR(140),
PRIMARY KEY(ISBN, TEXTO),
FOREIGN KEY(ISBN) REFERENCES BDET.LIVRO(ISBN)
	ON DELETE CASCADE ON UPDATE CASCADE
);


CREATE TABLE BDET.AUTOR(
ID			BIGINT		NOT NULL,
NOME		VARCHAR(15),
SOBRENOME	VARCHAR(15),
PRIMARY KEY(ID)
);


CREATE TABLE BDET.ESCREVE(
ID_AUTOR	INT		NOT NULL,
ISBN		BIGINT 	NOT NULL,
PRIMARY KEY(ID_AUTOR, ISBN),
FOREIGN KEY(ID_AUTOR) REFERENCES BDET.AUTOR(ID)
	ON DELETE RESTRICT ON UPDATE CASCADE,
FOREIGN KEY(ISBN) REFERENCES BDET.LIVRO(ISBN)
	ON DELETE RESTRICT ON UPDATE CASCADE
);


CREATE TABLE BDET.USUARIO(
USERNAME	VARCHAR(8)	NOT NULL	DEFAULT 'TEMP_USR',
SENHA		INT			NOT NULL	DEFAULT 0,
NOME		VARCHAR(15),
SOBRENOME	VARCHAR(15),
ENDERECO	VARCHAR(140),
CIDADE		VARCHAR[20],
SIGLA_ESTADO	CHAR(2),
CEP		char(8),
PRIMARY KEY(USERNAME),
FOREIGN KEY(SIGLA_ESTADO) REFERENCES BDET.ESTADO(SIGLA)
	ON DELETE RESTRICT ON UPDATE CASCADE
);


CREATE TABLE BDET.EMPRESA_CC(
EBANDEIRA	VARCHAR(10)	NOT NULL,

PRIMARY KEY(EBANDEIRA)
);


CREATE TABLE BDET.CARTAO(
BANDEIRA	VARCHAR(10)	NOT NULL UNIQUE,
NUMERO		VARCHAR(16)	NOT NULL UNIQUE,
DT_VALIDADE	INTERVAL,			
PRIMARY KEY(BANDEIRA, NUMERO),
FOREIGN KEY(BANDEIRA) REFERENCES BDET.EMPRESA_CC(EBANDEIRA)
	ON DELETE RESTRICT ON UPDATE CASCADE
);


CREATE TABLE BDET.CLIENTE(
USERNAME	VARCHAR(15)		NOT NULL,
CC_BANDEIRA	VARCHAR(10)		NOT NULL,
CC_NUMERO		CHAR(16)	NOT NULL,
PRIMARY KEY(USERNAME),
FOREIGN KEY(USERNAME) REFERENCES BDET.USUARIO(USERNAME)
	ON DELETE CASCADE ON UPDATE CASCADE,
FOREIGN KEY(CC_BANDEIRA) REFERENCES BDET.EMPRESA_CC(EBANDEIRA)
	ON DELETE RESTRICT ON UPDATE CASCADE,
FOREIGN KEY(CC_NUMERO) REFERENCES BDET.CARTAO(NUMERO)
	ON DELETE RESTRICT	ON UPDATE CASCADE
);


CREATE TABLE BDET.ADMINISTRADOR(
USERNAME	VARCHAR(8)	NOT NULL UNIQUE,
DT_CONTRAT	DATE		NOT NULL UNIQUE,
PRIMARY KEY(USERNAME, DT_CONTRAT),
FOREIGN KEY(USERNAME) REFERENCES BDET.USUARIO(USERNAME)
	ON DELETE RESTRICT ON UPDATE CASCADE
);


CREATE TABLE BDET.TELEFONE_ADM(
USERNAME	VARCHAR(8)	NOT NULL,
DT_CONTRAT	DATE		NOT NULL,
TELEFONE	INT,
PRIMARY KEY(USERNAME, DT_CONTRAT, TELEFONE),
FOREIGN KEY(USERNAME) REFERENCES BDET.ADMINISTRADOR(USERNAME)
	ON DELETE CASCADE ON UPDATE CASCADE,
FOREIGN KEY(DT_CONTRAT) REFERENCES BDET.ADMINISTRADOR(DT_CONTRAT)
	ON DELETE CASCADE ON UPDATE CASCADE
);


CREATE TABLE BDET.TRANSACAO(
USERNAME	VARCHAR(8)	NOT NULL UNIQUE,
DATA		DATE		NOT NULL UNIQUE,
HORA		TIME		NOT NULL UNIQUE,
CATEGORIA	VARCHAR(15),
VALOR_TOTAL	MONEY,
PRIMARY KEY (USERNAME, DATA, HORA),
FOREIGN KEY(USERNAME) REFERENCES BDET.USUARIO(USERNAME)
	ON DELETE SET DEFAULT ON UPDATE CASCADE
);


CREATE TABLE BDET.COLOCA_CARRINHO(
USERNAME	VARCHAR(15)	NOT NULL,
ISBN		BIGINT			NOT NULL,
QTD			INT,
PRIMARY KEY(USERNAME, ISBN),
FOREIGN KEY(USERNAME) REFERENCES BDET.CLIENTE(USERNAME)
	ON DELETE RESTRICT ON UPDATE CASCADE,
FOREIGN KEY(ISBN) REFERENCES BDET.LIVRO(ISBN)
	ON DELETE RESTRICT ON UPDATE CASCADE
);



CREATE TABLE BDET.PEDIDO(	 	 	 	 	 	 	 	 	 	 
USERNAME    VARCHAR(15)	NOT NULL,
DT_CONTRAT	DATE		NOT NULL,
ISBN	    BIGINT			NOT NULL,
DATA	    DATE,
HORA		TIME,
QTD			INT			DEFAULT 1,
PRIMARY KEY(USERNAME, DT_CONTRAT, ISBN),
FOREIGN KEY(USERNAME) REFERENCES BDET.ADMINISTRADOR(USERNAME)
	ON DELETE RESTRICT ON UPDATE CASCADE,
FOREIGN KEY(DT_CONTRAT) REFERENCES BDET.ADMINISTRADOR(DT_CONTRAT)
	ON DELETE RESTRICT	ON UPDATE CASCADE,
FOREIGN KEY(ISBN) REFERENCES BDET.LIVRO(ISBN)
	ON DELETE RESTRICT ON UPDATE CASCADE
);


CREATE TABLE BDET.CONTEM(	 	 	 	 	 	 	 	 	 	 
USERNAME	VARCHAR(8)	NOT NULL,
DATA		DATE		NOT NULL,
HORA		TIME		NOT NULL,
ISBN		BIGINT 		NOT NULL,
QTD			INT,
PRIMARY KEY(USERNAME, DATA, HORA, ISBN),
FOREIGN KEY(USERNAME) REFERENCES BDET.TRANSACAO(USERNAME)
	ON DELETE RESTRICT ON UPDATE CASCADE,
FOREIGN KEY(DATA) REFERENCES BDET.TRANSACAO(DATA)
	ON DELETE RESTRICT ON UPDATE CASCADE,
FOREIGN KEY(HORA) REFERENCES BDET.TRANSACAO(HORA)
	ON DELETE RESTRICT ON UPDATE CASCADE,
FOREIGN KEY(ISBN) REFERENCES BDET.LIVRO(ISBN)
	ON DELETE RESTRICT ON UPDATE CASCADE
);