-- --Insere Usuários
-- SELECT "ENG"."INSERE_USUARIO"(1234,'Ana');
-- SELECT "ENG"."INSERE_USUARIO"(2345,'Joao');
-- SELECT "ENG"."INSERE_USUARIO"(3456,'Maria');

-- --confirma usuarios
-- SELECT "ENG"."CONFIRMA_USUARIO"('Ana');
-- SELECT "ENG"."CONFIRMA_USUARIO"('Joao');
-- SELECT "ENG"."CONFIRMA_USUARIO"('Maria');

-- --Insere Grupos
-- SELECT "ENG"."INSERE_GRUPO"('Grupo1');
-- SELECT "ENG"."INSERE_GRUPO"('Grupo2');
-- SELECT "ENG"."INSERE_GRUPO"('Grupo3');

-- --Insere Usuarios no Grupo1
-- SELECT "ENG"."INSERE_USUARIO_EM_GRUPO"((SELECT USR."ID_GRUPO" AS IDGRUPO FROM "ENG"."GRUPO" USR WHERE USR."NM_GRUPO" = 'Grupo1'),
-- (SELECT USR."ID_USUARIO" AS IDUSR FROM "ENG"."USUARIO" USR WHERE USR."NM_LOGIN" = 'Ana'));
-- SELECT "ENG"."INSERE_USUARIO_EM_GRUPO"((SELECT USR."ID_GRUPO" AS IDGRUPO FROM "ENG"."GRUPO" USR WHERE USR."NM_GRUPO" = 'Grupo1'),
-- (SELECT USR."ID_USUARIO" AS IDUSR FROM "ENG"."USUARIO" USR WHERE USR."NM_LOGIN" = 'Joao'));
-- SELECT "ENG"."INSERE_USUARIO_EM_GRUPO"((SELECT USR."ID_GRUPO" AS IDGRUPO FROM "ENG"."GRUPO" USR WHERE USR."NM_GRUPO" = 'Grupo1'),
-- (SELECT USR."ID_USUARIO" AS IDUSR FROM "ENG"."USUARIO" USR WHERE USR."NM_LOGIN" = 'Maria'));

-- --Confirma Participacao
-- SELECT "ENG"."CONFIRMA_PARTICIPACAO"((SELECT USR."ID_USUARIO" AS IDUSR FROM "ENG"."USUARIO" USR WHERE USR."NM_LOGIN" = 'Ana'),
-- (SELECT USR."ID_GRUPO" AS IDGRUPO FROM "ENG"."GRUPO" USR WHERE USR."NM_GRUPO" = 'Grupo1'));
-- SELECT "ENG"."CONFIRMA_PARTICIPACAO"((SELECT USR."ID_USUARIO" AS IDUSR FROM "ENG"."USUARIO" USR WHERE USR."NM_LOGIN" = 'Joao'),
-- (SELECT USR."ID_GRUPO" AS IDGRUPO FROM "ENG"."GRUPO" USR WHERE USR."NM_GRUPO" = 'Grupo1'));
-- SELECT "ENG"."CONFIRMA_PARTICIPACAO"((SELECT USR."ID_USUARIO" AS IDUSR FROM "ENG"."USUARIO" USR WHERE USR."NM_LOGIN" = 'Maria'),
-- (SELECT USR."ID_GRUPO" AS IDGRUPO FROM "ENG"."GRUPO" USR WHERE USR."NM_GRUPO" = 'Grupo2'));

-- --Cria votações
--SELECT "ENG"."INSERE_VOTACAO"(0, 0, 10, 'teste de votacao1', 'votacao1', 'Shirata', '02/5/2010');
--SELECT "ENG"."INSERE_VOTACAO"(1, 0, 10, 'teste de votacao2', 'votacao2', 'Shirata', '12/1/2010');
--SELECT "ENG"."INSERE_VOTACAO"(1, 1, 10, 'teste de votacao3', 'votacao3', 'Shirata', '25/11/2010');

-- --InsereGrupos nas votações
--SELECT "ENG"."INSERE_PARTICIPANTE"((SELECT USR."ID_GRUPO" AS IDGRUPO FROM "ENG"."GRUPO" USR WHERE USR."NM_GRUPO" = 'Grupo1'), (SELECT --VT."ID_VOTACAO" FROM "ENG"."VOTACAO" VT WHERE VT."DS_TEMA" = 'teste de votacao1'));
--SELECT "ENG"."INSERE_PARTICIPANTE"((SELECT USR."ID_GRUPO" AS IDGRUPO FROM "ENG"."GRUPO" USR WHERE USR."NM_GRUPO" = 'Grupo2'), (SELECT --VT."ID_VOTACAO" FROM "ENG"."VOTACAO" VT WHERE VT."DS_TEMA" = 'teste de votacao2'));
--SELECT "ENG"."INSERE_PARTICIPANTE"((SELECT USR."ID_GRUPO" AS IDGRUPO FROM "ENG"."GRUPO" USR WHERE USR."NM_GRUPO" = 'Grupo3'), (SELECT --VT."ID_VOTACAO" FROM "ENG"."VOTACAO" VT WHERE VT."DS_TEMA" = 'teste de votacao3'));


-- --Cria 3 opcoes
--SELECT "ENG"."INSERE_OPCAO"('opcao1');
--SELECT "ENG"."INSERE_OPCAO"('opcao2');
--SELECT "ENG"."INSERE_OPCAO"('opcao3');

-- --Insere Opcoes na votacao 1
--SELECT "ENG"."INSERE_OPCAO_NA_VOT"((SELECT OP."ID_OPCAO" FROM "ENG"."OPCAO" OP WHERE OP."DS_OPCAO" = 'opcao1'), (SELECT VT."ID_VOTACAO" FROM --"ENG"."VOTACAO" VT WHERE VT."DS_TEMA" = 'teste de votacao1'));
--SELECT "ENG"."INSERE_OPCAO_NA_VOT"((SELECT OP."ID_OPCAO" FROM "ENG"."OPCAO" OP WHERE OP."DS_OPCAO" = 'opcao2'), (SELECT VT."ID_VOTACAO" FROM --"ENG"."VOTACAO" VT WHERE VT."DS_TEMA" = 'teste de votacao1'));
--SELECT "ENG"."INSERE_OPCAO_NA_VOT"((SELECT OP."ID_OPCAO" FROM "ENG"."OPCAO" OP WHERE OP."DS_OPCAO" = 'opcao3'), (SELECT VT."ID_VOTACAO" FROM --"ENG"."VOTACAO" VT WHERE VT."DS_TEMA" = 'teste de votacao1'));